spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/oms-poc
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema created by inventory-service Flyway migrations.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

inventory.service.base-url=http://localhost:8084
