spring.application.name=integration-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/integration-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true

identity.service.base-url=http://127.0.0.1:8086

spring.kafka.bootstrap-servers=localhost:9092

camel.component.kafka.brokers=localhost:9092
camel.component.kafka.group-id=integration-saga
